### ISSUE TITLE
14.2正式版

### ISSUE THREAD

**Issue by dourgulf** [RayJiang16/iOSDeviceSupport#1]
Xcode14.2正式版已经发布，可以更新正式版的了。
现在的版本，在14.2设备上调试会有这个报错：dyld_shared_cache_extract_dylibs failed，虽然，一般调试还是正常的。

**Comment by RayJiang16** [comment]
我没遇到过这个错误，我看了下 Xcode 12.2 Release 和 Xcode 12.2 RC1（即目前提供的资源） 中 14.2 DeviceSupport 的 md5 值是一致的。
你可以试下把 `~/Library/Developer/Xcode/iOS DeviceSupport/` 路径下的文件删除，再重启电脑看看这个问题有没有解决。

**Comment by dourgulf** [comment]
我提交了一个PR上来，更换这个版本之后，我这边没有报错了。
PS：我用的是Xcode14.1

**Comment by dourgulf** [comment]
似乎确实是一样的。。。
我把PR关了。

**Comment by dourgulf** [comment]
恢复到您提供的版本，重接一下数据线，没再报错了。我关闭这个issue了。
